# Generated by Django 5.0.2 on 2024-02-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "counter",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Счетчик просмотров"
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок контента",
                "verbose_name_plural": "Блоки контента",
                "ordering": ("order",),
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Активно"
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
                "ordering": ("url",),
            },
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.content",
                    ),
                ),
                ("bitrate", models.PositiveIntegerField(verbose_name="Битрейт")),
            ],
            options={
                "verbose_name": "Аудио",
                "verbose_name_plural": "Аудио",
                "ordering": ("order",),
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("pages.content",),
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.content",
                    ),
                ),
                ("some_text", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Текст",
                "verbose_name_plural": "Текст",
                "ordering": ("order",),
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("pages.content",),
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pages.content",
                    ),
                ),
                ("video_url", models.URLField(verbose_name="Ссылка на файл")),
                ("subtitle_url", models.URLField(verbose_name="Ссылка на субтитры")),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
                "ordering": ("order",),
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("pages.content",),
        ),
        migrations.AddField(
            model_name="content",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.page",
                verbose_name="Страница",
            ),
        ),
    ]
