# Generated by Django 5.0.2 on 2024-02-20 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_content_counter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ("id",),
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
            },
        ),
        migrations.RemoveField(
            model_name="page",
            name="url",
        ),
    ]
