# Generated by Django 5.0.2 on 2024-02-20 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_alter_page_options_remove_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content",
                to="pages.page",
                verbose_name="Страница",
            ),
        ),
    ]
